# Generated by Django 4.0.4 on 2022-05-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_img'),
        ('posts', '0003_alter_post_created_date'),
    ]

    operations = [
    ]
